AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Flare Api for Jira
Resources:
  alexaskillkitsdkfactskill:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs4.3
      CodeUri: .
      Description: Flare Api for Jira
      MemorySize: 128
      Timeout: 7
      Role: !<tag:yaml.org,2002:js/undefined> ''
